SCR_EntityCatalogMultiList {
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{5C54F92C13994FAF}" {
   m_sEntityPrefab "{10F227D31D426446}Prefabs/Groups/BLUFOR/Group_DE_BGS_Post.et"
  }
  SCR_EntityCatalogEntry "{5C54F92C1389DCDD}" {
   m_sEntityPrefab "{6781E5B8818290F0}Prefabs/Groups/BLUFOR/Group_DE_BW_Crew.et"
  }
  SCR_EntityCatalogEntry "{5C54F92C127F0004}" {
   m_sEntityPrefab "{FFDA92EF494794CC}Prefabs/Groups/BLUFOR/Group_DE_BW_Heli.et"
  }
  SCR_EntityCatalogEntry "{5C54F92C12486573}" {
   m_sEntityPrefab "{093CA01C354FE17A}Prefabs/Groups/BLUFOR/Group_DE_BW_HQ.et"
  }
  SCR_EntityCatalogEntry "{5C54F92C123CDCAB}" {
   m_sEntityPrefab "{921BBEC64AFE5A29}Prefabs/Groups/BLUFOR/Group_DE_BW_Squad.et"
  }
  SCR_EntityCatalogEntry "{5C54F92C12103EC3}" {
   m_sEntityPrefab "{B9ED8E1CC65E339D}Prefabs/Groups/BLUFOR/Group_DE_BW_Squad2.et"
  }
  SCR_EntityCatalogEntry "{5C54F92C12EF81F1}" {
   m_bEnabled 0
  }
  SCR_EntityCatalogEntry "{5C54F92C112F3EB0}" {
   m_bEnabled 0
  }
  SCR_EntityCatalogEntry "{611EBEA3C6943C7D}" {
   m_bEnabled 0
  }
  SCR_EntityCatalogEntry "{611EBEA3C52ED205}" {
   m_bEnabled 0
  }
  SCR_EntityCatalogEntry "{5C54F92C125401E3}" {
   m_bEnabled 0
  }
  SCR_EntityCatalogEntry "{611EBEA3DC880982}" {
   m_bEnabled 0
  }
  SCR_EntityCatalogEntry "{611EBEA3C7B8F4EB}" {
   m_bEnabled 0
  }
  SCR_EntityCatalogEntry "{611EBEA3DC4C7579}" {
   m_bEnabled 0
  }
  SCR_EntityCatalogEntry "{611EBEA3C4688AD6}" {
   m_bEnabled 0
  }
  SCR_EntityCatalogEntry "{61A6B5C58502F1DC}" {
   m_bEnabled 0
  }
  SCR_EntityCatalogEntry "{61A6B5C584174869}" {
   m_bEnabled 0
  }
  SCR_EntityCatalogEntry "{62488309BDE25100}" {
   m_bEnabled 0
  }
  SCR_EntityCatalogEntry "{6248E9F73C84AE2B}" {
   m_bEnabled 0
  }
  SCR_EntityCatalogEntry "{65DEE29CC8684B30}" {
   m_bEnabled 0
  }
  SCR_EntityCatalogEntry "{68C955EE8A1A229D}" {
   m_bEnabled 0
  }
  SCR_EntityCatalogEntry "{68C955EE8500C92B}" {
   m_bEnabled 0
  }
  SCR_EntityCatalogEntry "{68C955EE822E6426}" {
   m_bEnabled 0
  }
  SCR_EntityCatalogEntry "{68C955EEBF7610A8}" {
   m_bEnabled 0
  }
  SCR_EntityCatalogEntry "{68C955EEBA31C538}" {
   m_bEnabled 0
  }
  SCR_EntityCatalogEntry "{68C955EEB0862631}" {
   m_bEnabled 0
  }
  SCR_EntityCatalogEntry "{68C955EEAD82EAFA}" {
   m_bEnabled 0
  }
  SCR_EntityCatalogEntry "{68C955EEAA9E38FD}" {
   m_bEnabled 0
  }
 }
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{605697820C856F25}" {
   m_aEntities {
    SCR_EntityCatalogEntry "{5CCEA181AD29F55C}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{5CCEA181ADF83294}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{5CCEA181ACAFE503}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{5CCEA181AB034B38}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{5CCEA181ABCF2648}" {
     m_sEntityPrefab ""
     m_bEnabled 0
    }
   }
  }
 }
}