SystemSettings : "{45C53F06BA17238D}configs/Systems/SystemsConfig.conf" {
 Systems {
  SCR_GarbageSystem "{5F10E7EA29B0EDEC}" {
   Rules {
    EntityClassGarbageRule "{60713063DB480AC7}" {
     Priority 60000
     Lifetime 3600
    }
    ComponentClassGarbageRule "{6071306334D2708C}" {
     Priority 60000
     Lifetime 3600
    }
    EntityClassGarbageRule "{60713063F62751A3}" {
     Priority 60000
     Lifetime 3600
    }
    EntityClassGarbageRule "{68D007EED61D2BDC}" {
     Priority 60000
     Filter "SCR_ChimeraCharacter"
     Lifetime 3600
    }
   }
  }
 }
}