FactionIdentity {
 SocialIdentity SocialIdentity "{68CA81EDB474F950}" {
  NamesConfig {
   "Noah"
   "Leo"
   "Paul"
   "Matteo"
   "Ben"
   "Finn"
   "Felix"
   "Engel"
   "Ludolf"
   "Reinhard"
   "Severin"
   "Carl"
   "Günter"
   "Hänsel"
   "Ludwig"
   "Erich"
   "Oskar"
   "Rainer"
   "Wolf"
   "Dirk"
   "Hubert"
   "Jürgen"
   "Klaus"
  }
  SurnamesConfig {
   "Müller"
   "Schmidt"
   "Schneider"
   "Fischer"
   "Meyer"
   "Weber"
   "Schäfer"
   "Wagner"
   "Becker"
   "Bauer"
   "Hoffmann"
   "Schulz"
   "Koch"
   "Richter"
   "Klein"
   "Schröder"
   "Neumann"
   "Braun"
   "Zimmermann"
   "Hartmann"
   "Köhler"
   "Lange"
   "Vogel"
  }
 }
}