SCR_EntityCatalogMultiList {
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{691AB3474B5C8FBC}" {
   m_sEntityPrefab "{BA010C4C82F3DE92}Prefabs/Characters/Factions/OPFOR/USSR_Army/Character_USSR_CC.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{691AB3474B5C8FD5}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{691AB3474B5C8FD7}" {
     m_eSlotTypes GROUP_SMALL
    }
   }
  }
  SCR_EntityCatalogEntry "{691AB3474C5982DE}" {
   m_sEntityPrefab "{C8FABF6F093DA775}Prefabs/Characters/Factions/OPFOR/USSR_Army/Character_USSR_HeliCrew.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{691AB3474C598262}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{691AB3474C598265}" {
     m_eSlotTypes GROUP_SMALL
    }
   }
  }
 }
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{68CA81EE4B4AB9F7}" {
   m_aEntities {
    SCR_EntityCatalogEntry "{68CA81EE4B4AB9F4}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{68CA81EE4B4AFBAA}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{68CA81EE4B4AFBA9}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{68CA81EE4B4AFBA4}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{68CA81EE4B4A281B}" {
     m_sEntityPrefab ""
     m_bEnabled 0
    }
   }
  }
 }
}