SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{605697836F02AFD9}" {
   m_aEntities {
    SCR_EntityCatalogEntry "{63229A276327C12F}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{63229A274340C655}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{652D37200671A25D}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{68CB682A03617E39}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{65721BAA3C523CE8}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{65721BAA3F2E83E6}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{65330885622834D8}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6532E3E8599418E2}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6532E3E858B3B527}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6532E3E85A7FD81B}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6532E3E84FD555E2}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6532E3E987788726}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6532E3E9B9CE88C3}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6532E3E9BC53A118}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6532E3E9BE61782B}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6532E3E9A97F329E}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6532E3E9A89418FB}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6532E3E9AB39B2CB}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6532E3E9AA7D7A26}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6532E3E9AD717E23}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6532E3E9ACDBAE4F}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6532E3E9AFCBF448}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6532E3E9AEFF1B6F}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6532E3E9A1AF5503}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6532E3E97EE0BADD}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6532E3E9712672A8}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6532E3E976EB4E21}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6532E3E9690B5C25}" {
     m_bEnabled 0
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{605697836CAAD3A0}" {
   m_aEntities {
    SCR_EntityCatalogEntry "{60C3186F9AF00BEA}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{62B10747441A3F3D}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{630A1A7A6544E0A2}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{630A1A7A6A65CB50}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{65B11D63F5516D1E}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{630A1A7A55D78C44}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{68E29E972A6280DF}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{68E29E972D7EAA50}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{68E29E972C06B9EE}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{68E29E972F737647}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{68E29E972FBA567B}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{68E29E972EECFFB8}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{68E29E9721F867ED}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{68E29E97203916CF}" {
     m_bEnabled 0
    }
   }
  }
 }
}