SCR_Faction : "{E7B7EA4823DD81F0}Configs/Factions/BLUFOR.conf" {
 "Identity of soldiers" FactionIdentity "{570D128F4022EF5A}" : "{013289EB9B10F08B}Configs/Identities/FactionIdentity_BRD.conf" {
 }
 m_CallsignInfo SCR_FactionCallsignInfo "{5DA0F2A6677ADA9E}" {
  m_aPlatoonNames {
   SCR_CallsignInfo "{6927532BD0130EF2}" {
    m_sCallsign "5"
   }
  }
  m_aSquadNames {
   SCR_CallsignInfo "{6927532BD67DFB40}" {
    m_sCallsign "5"
   }
   SCR_CallsignInfo "{6927532BD7327283}" {
    m_sCallsign "6"
   }
  }
  m_sCallsignGroupFormat "%1 %3"
 }
 m_aEntityCatalogs {
  SCR_EntityCatalogMultiList "{5C68A0EE815FA292}" : "{B56E8B4D4B195559}Configs/EntityCatalog/US/Characters_EntityCatalog_US.conf" {
  }
  SCR_EntityCatalogMultiList "{5C9E82F29B327997}" : "{D83A5EFEEF6CBF61}Configs/EntityCatalog/US/Vehicles_EntityCatalog_US.conf" {
  }
  SCR_EntityCatalogMultiList "{5C68A0EE8B97CA50}" : "{4E70E7C4C2C17D4A}Configs/EntityCatalog/US/Groups_EntityCatalog_US.conf" {
  }
 }
 m_FactionHomeTerritoryConfig SCR_FactionHomeTerritoryConfig "{5AEE94D54FB58C33}" : "{9490D2411364A503}Configs/Identities/Territories/FactionHomeTerritory_BRD.conf" {
 }
}