SCR_MissionHeaderCombatOps {
 World "{77E41C57A6CF04C4}world/misson2.ent"
 m_sName "«Семь дней до реки Рейн» Эпизод 2"
 m_sAuthor "[BKLT]Zakat616"
 m_sDetails "После операции США \"Мертвый Якорь\" и применения тактического ЯО, горячую фазу конфликта уже не остановить. Страны ОВД перешли в наступление на территории Европы."\
 ""\
 "28 августа 1988г войска Национальной народной армии должны перейти границу ГДР и ФРГ, ликвидировать возможное сопротивление и организовать плацдарм, для дальнейшего продвижения войск ОВД к Рурскому бассейну. Прорыв границы силами Национальной народной армии удался. В приграничной зоне находится РЛС сил ФРГ, которую войска ННА должны уничтожить."
 m_sLoadingScreen "{311233DD390251B2}UI/map_BCR.edds"
 m_sPreviewImage "{311233DD390251B2}UI/map_BCR.edds"
 m_sGameMode "#AR-ServerBrowser_ServerScenario"
 m_iPlayerCount 128
 m_bOverrideScenarioTimeAndWeather 1
 m_bRandomStartingDaytime 1
 m_aTaskTypesAvailable {
  SCR_ScenarioFrameworkTaskType "{6922B8A306D5F916}" {
   m_eTypeOfTask DELIVER
  }
  SCR_ScenarioFrameworkTaskType "{6922B8A306CB5C34}" {
   m_eTypeOfTask DESTROY
  }
  SCR_ScenarioFrameworkTaskType "{6922B8A306CB5C08}" {
   m_eTypeOfTask CLEAR_AREA
  }
  SCR_ScenarioFrameworkTaskType "{6922B8A306CB5C09}" {
   m_eTypeOfTask KILL
  }
  SCR_ScenarioFrameworkTaskType "{6922B8A306CB5C0A}" {
   m_eTypeOfTask DEFEND
  }
 }
}