SCR_MissionHeaderCombatOps {
 World "{95F0CE58FAB2726B}world/misson.ent"
 m_sName "«Семь дней до реки Рейн» Эпизод 1"
 m_sAuthor "[BKLT]Zakat616"
 m_sDetails "После операции США \"Мертвый Якорь\" и применения тактического ЯО, горячую фазу конфликта уже не остановить. Страны ОВД перешли в наступление на территории Европы."\
 ""\
 "28 августа 1988г войска Национальной народной армии должны перейти границу ГДР и ФРГ, ликвидировать возможное сопротивление и организовать плацдарм, для дальнейшего продвижения войск ОВД к Рурскому бассейну. Ранним утром войска Национальной народной армии перешли в наступление. Целью являются приграничные базы Бундесвера и военный аэродром."
 m_sIcon "{311233DD390251B2}UI/map_BCR.edds"
 m_sLoadingScreen "{311233DD390251B2}UI/map_BCR.edds"
 m_sPreviewImage "{311233DD390251B2}UI/map_BCR.edds"
 m_sGameMode "#AR-ServerBrowser_ServerScenario"
 m_iPlayerCount 128
 m_bOverrideScenarioTimeAndWeather 1
 m_iStartingHours 0
 m_iStartingMinutes 40
 m_aTaskTypesAvailable {
  SCR_ScenarioFrameworkTaskType "{6916A594A4A14D78}" {
   m_eTypeOfTask DELIVER
  }
  SCR_ScenarioFrameworkTaskType "{6916A594A4A14D45}" {
   m_eTypeOfTask DESTROY
  }
  SCR_ScenarioFrameworkTaskType "{6916A594A4A14D47}" {
   m_eTypeOfTask CLEAR_AREA
  }
  SCR_ScenarioFrameworkTaskType "{6916A594A4A12918}" {
   m_eTypeOfTask KILL
  }
  SCR_ScenarioFrameworkTaskType "{6916A594A4A12907}" {
   m_eTypeOfTask DEFEND
  }
 }
}