SCR_MissionHeaderCombatOps {
 World "{00EE74DF526DEBB4}world/misson3.ent"
 m_sName "«Семь дней до реки Рейн» Эпизод 3"
 m_sAuthor "[BKLT]Zakat616"
 m_sDetails "После операции США \"Мертвый Якорь\" и применения тактического ЯО, горячую фазу конфликта уже не остановить. Страны ОВД перешли в наступление на территории Европы."\
 ""\
 "28 августа 1988г войска Национальной народной армии должны перейти границу ГДР и ФРГ, ликвидировать возможное сопротивление и организовать плацдарм, для дальнейшего продвижения войск ОВД к Рурскому бассейну.Бундесвер перешел в контратаку. Силам ННА нужно удержать аэродром недавно захваченный в приграничной территории."
 m_sLoadingScreen "{311233DD390251B2}UI/map_BCR.edds"
 m_sPreviewImage "{311233DD390251B2}UI/map_BCR.edds"
 m_sGameMode "#AR-ServerBrowser_ServerScenario"
 m_iPlayerCount 128
 m_bOverrideScenarioTimeAndWeather 1
 m_iStartingHours 13
 m_bRandomStartingDaytime 1
 m_aTaskTypesAvailable {
  SCR_ScenarioFrameworkTaskType "{6922D06344F9B8A8}" {
   m_eTypeOfTask DELIVER
  }
  SCR_ScenarioFrameworkTaskType "{6922D06344F9B8BD}" {
   m_eTypeOfTask DESTROY
  }
  SCR_ScenarioFrameworkTaskType "{6922D06344F9B8BE}" {
   m_eTypeOfTask CLEAR_AREA
  }
  SCR_ScenarioFrameworkTaskType "{6922D06344F9B8BF}" {
   m_eTypeOfTask KILL
  }
  SCR_ScenarioFrameworkTaskType "{6922D06344F9B8B0}" {
   m_eTypeOfTask DEFEND
  }
 }
}